default: &default
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
#  username:
#  password:

development:
  <<: *default
  database: poll_development

test:
  <<: *default
  database: poll_processing_test

production:
  <<: *default
  database: poll_production
